translate_telegram: true
channels:
  - telegram
  - durov
  - techcrunchcom
  - technology
  - aipost
  - Cyber_Security_Channel
  - cyber_security_feed
  - cybernotif
  - BBCWorld
  - reutersworldchannel
